app = "nexentra"

[build]
  dockerfile = "dockerfile"

[[services]]
  internal_port = 8000  # Backend running on port 8000
  protocol = "tcp"

  [[services.ports]]
    port = 80  # Expose backend on port 80 for HTTP
    handlers = ["http"]

  [[services.ports]]
    port = 443  # Expose backend on port 443 for HTTPS
    handlers = ["tls", "http"]

[env]
  REACT_APP_API_URL = "https://nexentra.fly.dev"