import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/*
        suppressHydrationWarning: Some browser extensions (e.g. Grammarly) inject
        attributes into DOM nodes after server render which causes React hydration
        mismatches. Adding this flag silences the mismatch for the body element.
        If you can, prefer disabling the extension or ensuring server and client
        render the same attributes.
      */}
      <body
        suppressHydrationWarning
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
